title: Eat Sheets
author: John Chang
url: https://jrcpl.us
baseurl: /EatSheets
production_url: https://jrcpl.us/EatSheets

collections:
  cuisines:
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
